name: Generate static pages

on:
  push:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@master
      - name: npm install, test and build
        run: |
          npm install
          npm run build
        
      - name: Deploy on GitHub Pages
        uses: alex-page/blazing-fast-gh-pages-deploy@v1.1.0
        with:
          repo-token: ${{ secrets.GH_PAT }}
          site-directory: './dist'
          deploy-branch: master
