name: Create static site

on:
  push:
    branches:
    - dev

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v1
        with:
          ref: dev
      - name: npm install, test and build
        run: |
          npm install
          npm run build
        
      - name: Deploy on GitHub Pages
        uses: alex-page/blazing-fast-gh-pages-deploy@v1.1.0
        with:
          site-directory: './dist'
          deploy-branch: master
          commit-message: 'Deploy site'
